server:
  port: 9632
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/securitydemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root123

