server:
  port: 8635
#################################
 #实现web登录自定义方式一       #####
#spring:                    #####
#  security:                #####
#    user:                  #####
#      name: root           #####
#      password: root123    #####
#################################

